### ISSUE TITLE
Does not handle aiohttp TimeoutExceptions

### ISSUE THREAD

**Issue by ThorntonMatthewD** [Bot-detector/bot-detector-scraper#3]
Program crashes if any requests via aiohttp timeout, which unfortunately can be an issue from time to time.

I have not been able to replicate it in the last couple of days, but I know it's still there. I'll keep an eye of the logs and post more info as I receive it. I just don't want to forget about this so I'm opening up the issue.

**Comment by extreme4all** [comment]
i believe it should be this timeout:
asyncio.exceptions.TimeoutError 
we should write an exception for it.

depending on where this occurs, we might need todo different actions
