### ISSUE TITLE
Bot Graveyard Integration

### ISSUE THREAD

**Issue by ThorntonMatthewD** [Bot-detector/bot-detector-scraper#5]
Was thinking of adding a `to_broadcast` column to the Players table, default tinyint=0, and having a `username['to_broadcast'] = 1` call here: https://github.com/Bot-detector/bot-detector-scraper/blob/4b9b117ca167d20c8d5ea28e974381030648a700/batching.py#L150

Separately from the scraper logic we could have a small script pull 50 names at a time with to_broadcast=1, send them to the graveyard via webhook, and upon success update those players' to_broadcast=0.

**Comment by extreme4all** [comment]
we can use the database as persistence, but I'm not really in favor of that.
why don't we push directly to the discord via the scraper.
or we could post it to an api of our discord bot, but this would require us to have an api on our discord bot.

**Comment by ThorntonMatthewD** [comment]
I think doing it from the scraper is fine. I guess there can be a worker that pops 50 names at a time from a global list of banned folks? We can try it and see how much of a backup we get in clearing the list versus how fast we're adding to it. The Discord rate limit prevents us from going too crazy.

**Comment by extreme4all** [comment]
ideally i'd like to do it via an api on the discord bot, this could be useful for other things.
but short term some new global variable with all the new bans, where we pop them of by the discord api rate limit would be just fine
